/**
 * Takes a printedBill (from printBill.js) and "tags" it: Returns an array of autogenerated tags and subjects.
 * @param {object} bill - JSON bill (result from printBill.js)
 * @param {function} callback - Callback
 * @return {object} - An array of generated tags for the bill
 * @example
 * getBill("BILLSTATUS-115sres99", function(res){
 *   printBill(res, function(parsedResult){
 *     tagBill(parsedResult, function(tags){
 *        //tags is an array of tags
 *     })
 *   });
 * });
 */

var tagBill = function(bill, callback){
  if(typeof bill != "object") throw new TypeError("'bill' needs to be an object");
  if(callback == null) throw new TypeError("A callback needs to be included");

  try{
    var tags = [];

    callback(tags);
  }
  catch(e){
    throw new Error("JSON supplied must be a valid bill");
  }
};

module.exports = tagBill;
