var retext = require('retext');
var keywords = require('retext-keywords');
var fs = require('fs');
var nlcstToString = require('nlcst-to-string');

/**
 * Takes a printedBill (from printBill.js) and "tags" it: Returns an array of autogenerated tags and subjects.
 * @param {object} bill - JSON bill (result from printBill.js)
 * @param {function} callback - Callback
 * @return {object} - An array of generated tags for the bill
 * @example
 * getBill("BILLSTATUS-115sres99", function(res){
 *   printBill(res, function(parsedResult){
 *     tagBill(parsedResult, function(tags){
 *        //tags is an array of tags
 *     });
 *   });
 * });
 */

var tagBill = function(bill, callback){
  if(typeof bill != "object") throw new TypeError("'bill' needs to be an object");
  if(callback == null) throw new TypeError("A callback needs to be included");
  if(!("head" in bill) || !("body" in bill)) throw new TypeError("The bill supplied needs to be the output of printBill.js");

  //TODO: make max amount of tags an option

  try{
    var corpus = bill.body
    .replace(/\(\w+\)/gi, "")
    .replace(/[^a-z\n ]/gi, "")
    .replace(/ {2,}/g, " "); //Take the body and strip away all non letters

    var wordsToExcludeFromTags = ["paragraph", "none"]; //TODO: Update this list of words

    wordsToExcludeFromTags.forEach(function(word){
      corpus = corpus.replace(new RegExp(word, "gi"), "");
    });

    var tags = [];

    retext().use(keywords, {maximum: 15}).process(corpus, function (err, file) {
      if (err) throw err;

      file.data.keywords.forEach(function (keyword) {
        tags.push(nlcstToString(keyword.matches[0].node).toLowerCase());
      });
    });

    callback(tags);
  }
  catch(e){
    throw new Error("JSON supplied must be a valid bill");
  }
};

module.exports = tagBill;
